workflow:
    - second
    - third
shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo Starting main job!
            - set_meta: /opt/sd/meta set "foo" "foobar"
    second:
        steps:
            - print: echo Starting second job!
            - check_meta: test "foobar" = `/opt/sd/meta get "foo"`
            - set_meta: /opt/sd/meta set "bar" "barbaz"
    third:
        steps:
            - print: echo Starting third job!
            - check_meta: test "barbaz" = `/opt/sd/meta get "bar"`
